from mahilo.agent import BaseAgent
class SynthesisAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            type='synthesis_agent',
            name='synthesis_agent',
            description="This helper makes a short story from all the words.",
        )
    def generate_summary(self, text: str, paraphrased: str) -> str:
        """Generates a summary."""
        print(f"SynthesisAgent: generate_summary called with: {text}, {paraphrased}")  # for debugging
        return f"This is a summary generated by agent. Received messages: {text}, {paraphrased}"
